### ISSUE TITLE
Digital colour article: Broken link

### ISSUE THREAD

**Issue by Staudey** [Pomax/Pomax.github.io#25]
The first link in your digital colour article (http://pomax.github.io/1436836360570/we-are-really-terrible-at-digital-colours-and-digital-photography) is broken, the one to the wikipedia page for the color "Ao". It's missing the parenthesis at the end, which shows up in the text instead.

**Comment by Pomax** [comment]
yeah, it appears that the `marked` library is converting the Markdown syntax incorrectly. The syntax is using `[青 ("ao")](https://en.wikipedia.org/wiki/Ao_%28color))` but somehow the md parser is mangling it so that the part-of-the-URL parenthesis is treated as the markdown link syntax =(

Filed the issue over at https://github.com/chjj/marked/issues/619 but in the mean time I may need to turn that into some flat HTML markup. Thanks for letting me know!

**Comment by Pomax** [comment]
replaced MD syntax with HTML syntax for this link, if you find another link that doesn't work (I didn't see one cursorily but I may have missed one) do let me know!

**Comment by Staudey** [comment]
As a workaround you could probably also use `%29` instead of the parenthesis

**Comment by Pomax** [comment]
The blog allows for plain html so for now I can use `<a>`
